config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls', namespace='diary')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path
from diary.apps import DiaryConfig
from diary.views import base, DiaryListView, DiaryDetailView, DiaryCreateView, DiaryUpdateView, DiaryDeleteView, \
    DiaryPersonalListView

app_name = DiaryConfig.name

urlpatterns = [
    path('', base, name='base'),
    path('diary/', DiaryListView.as_view(), name='diary_list'),
    path('diary_personal/', DiaryPersonalListView.as_view(), name='diary_personal_list'),
    path('diary/create', DiaryCreateView.as_view(), name='diary_create'),
    path('diary/<int:pk>/', DiaryDetailView.as_view(), name='diary_detail'),
    path('diary/update/<int:pk>/', DiaryUpdateView.as_view(), name='diary_update'),
    path('diary/delete/<int:pk>/', DiaryDeleteView.as_view(), name='diary_delete'),
]

diary/models.py
from django.db import models
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Diary(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    image = models.ImageField(upload_to='diary/image', verbose_name='Превью события', **NULLABLE)
    context = models.TextField(verbose_name='Описание события')
    date_event = models.CharField(max_length=20, verbose_name='Дата события', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи', **NULLABLE)
    is_active = models.BooleanField(default=True, help_text='Разрешить эту запись видеть всем?')
    owner = models.ForeignKey(User, verbose_name='Владелец', on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Запись дневника'
        verbose_name_plural = 'Записи дневника'

diary/forms.py
from django.forms import ModelForm
from diary.models import Diary


class DiaryUpdateForm(ModelForm):
    class Meta:
        model = Diary
        fields = ('title', 'image', 'context', 'date_event', 'is_active')

diary/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from diary.forms import DiaryUpdateForm
from diary.models import Diary


def base(request):
    return render(request, 'base.html')


class DiaryListView(LoginRequiredMixin, ListView):
    model = Diary
    template_name = 'diary/diary_list.html'

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        if self.request.user.is_superuser:
            qs = Diary.objects.all()
        else:
            qs = Diary.objects.filter(is_active=True)
        if query:
            qs = qs.filter(Q(title__icontains=query) | Q(context__icontains=query))
        return qs.order_by('-created_at')


class DiaryDetailView(LoginRequiredMixin, DetailView):
    model = Diary
    template_name = 'diary/diary_detail.html'


class DiaryCreateView(CreateView):
    model = Diary
    fields = ('title', 'image', 'context', 'date_event', 'is_active')
    success_url = reverse_lazy('diary:diary_list')

    def form_valid(self, form):
        diary = form.save()
        user = self.request.user
        diary.owner = user
        diary.save()
        return super().form_valid(form)


class DiaryUpdateView(LoginRequiredMixin, UpdateView):
    model = Diary
    form_class = DiaryUpdateForm
    success_url = reverse_lazy('diary:diary_list')

    def get_queryset(self):
        return Diary.objects.filter(owner=self.request.user)


class DiaryDeleteView(LoginRequiredMixin, DeleteView):
    model = Diary
    success_url = reverse_lazy('diary:diary_list')


class DiaryPersonalListView(LoginRequiredMixin, ListView):
    model = Diary
    template_name = 'diary/diary_personal_list.html'

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        qs = Diary.objects.filter(owner=self.request.user).order_by('-created_at')
        if query:
            qs = qs.filter(Q(title__icontains=query) | Q(context__icontains=query))
        return qs.order_by('-created_at')

diary/templates/diary/diary_confirm_delete.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<style>
    body {
        background: url('{% static 'background/bck.jpg' %}') no-repeat center center fixed;
        background-size: cover;
    }
    .custom-card {
        width: 30%;
        max-width: 600px;
        box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
    }
</style>
<div class="container d-flex align-items-center justify-content-center" style="min-height: 100vh;">
    <div class="custom-card card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p>Хотите удалить запись "{{ object.title }}" ?</p>
                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-primary">Подтвердить</button>
                    <a class="btn btn-secondary" href="{% url 'diary:diary_list' %}">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% include 'includes/footer.html' %}

diary/templates/diary/diary_detail.html
{% load static %}
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyWay - {{ diary.title }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        body {
            background: url('{% static 'background/bck.jpg' %}') no-repeat center center fixed;
            background-size: cover;
        }

        .detail-container {
            max-width: 800px;
            margin: 50px auto;
            background-color: white;
            border: 1px solid #ced4da;
            border-radius: 5px;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            position: relative;
        }

        .detail-title {
            color: #4e73df;
        }

        .detail-image {
            width: 50%;
            height: auto;
            object-fit: cover;
            border-radius: 5px;
            margin-bottom: 20px;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

        .button-group {
            position: absolute;
            bottom: 20px;
            right: 20px;
        }

        .button-group .btn {
            margin-left: 10px;
        }
    </style>
</head>

<body>
{% include 'includes/inc_menu.html' %}

<div class="container detail-container">
    <h1 class="detail-title">{{ object.title }}</h1>
    <p><strong>Дата:</strong> {{ object.date_event }}</p>

    {% if object.image %}
    <img src="{{ object.image.url }}" alt="Изображение записи" class="detail-image">
    {% endif %}

    <p>{{ object.context }}</p>
    <p><strong>Дата создание записи:</strong> {{ diary.created_at }}</p>

    <div class="button-group">
        {% if request.user.is_superuser or request.user == object.owner %}
        <form action="{% url 'diary:diary_delete' object.pk %}" method="GET" style="display:inline;">
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
        <a href="{% url 'diary:diary_update' diary.pk %}" class="btn btn-primary">Изменить запись</a>
        {% endif %}

        <a href="{% url 'diary:diary_list' %}" class="btn btn-primary">Назад</a>
    </div>

</div>

{% include 'includes/footer.html' %}
</body>
</html>

diary/templates/diary/diary_form.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<style>
    body {
        background: url('{% static 'background/bck.jpg' %}') no-repeat center center fixed;
        background-size: cover;
    }
</style>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">
                    <h5>
                        {% if object %}
                        Редактирование записи
                        {% else %}
                        Создание записи
                        {% endif %}
                    </h5>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-flex justify-content-between mt-3">
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                            <a class="btn btn-secondary" href="{% url 'diary:diary_list' %}">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'includes/footer.html' %}

diary/templates/diary/diary_list.html
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyWay - Все записи</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        body {
            background: url('{% static 'background/bck.jpg' %}') no-repeat center center fixed;
            background-size: cover;
        }

        .entries-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            gap: 20px;
            margin-top: 50px;
            max-width: 1000px;
            margin-left: auto;
            margin-right: auto;
        }

        .entry {
            background-color: white;
            border: 1px solid #ced4da;
            border-radius: 5px;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            flex: 1 0 200px;
            max-width: 300px;
        }

        .entry h3 {
            margin: 0;
            color: #4e73df;
        }

        .entry-title-link {
            font-size: 1.5rem;
            color: #4e73df;
            text-decoration: none;
        }

        .entry p {
            margin-top: 10px;
        }

        .btn-primary {
            margin-bottom: 20px;
        }

        .entry img {
            width: 150px;
            height: 150px;
            object-fit: cover;
            border-radius: 5px;
            margin-bottom: 10px;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

        .search-form {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-bottom: 20px;
        }

        .search-input {
            margin-bottom: 21px;
            width: 250px;
            height: 38px;
            margin-right: 10px;
            padding: 0.375rem 0.75rem;
        }

        .search-button {
            height: 38px;
            padding: 0.375rem 0.75rem;
        }

        .hidden-note {
            color: red;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .no-results-message {
            color: black;
            text-align: center;
            margin-top: 20px;
            font-size: 3rem;
        }
    </style>
</head>

{% include 'includes/inc_menu.html' %}

<body>
<div class="container text-center">
    <h1 style="color: white; text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;">
        Публикации пользователей:
    </h1>
    <a href="{% url 'diary:diary_create' %}" class="btn btn-primary mb-3">Добавить запись</a>
    <form method="GET" action="{% url 'diary:diary_list' %}" class="search-form">
        <input type="text" name="q" placeholder="Поиск по записям"
               value="{{ request.GET.q }}" class="form-control search-input"/>
        <button type="submit" class="btn btn-primary search-button">Поиск</button>
    </form>
</div>

<div class="container">
    <div class="entries-container">
        {% for diary in object_list %}
        <div class="entry">
            {% if not diary.is_active and request.user.is_superuser %}
            <p class="hidden-note">Скрытая запись</p>
            {% endif %}
            <h3>
                <a href="{% url 'diary:diary_detail' diary.pk %}" class="entry-title-link">{{ diary.title }}</a>
            </h3>
            <p><strong>Дата:</strong> {{ diary.date_event }}</p>
            {% if diary.image %}
            <img src="{{ diary.image.url }}" alt="Изображение записи">
            {% endif %}
            <p>{{ diary.context|truncatewords:10 }}</p>
        </div>
        {% endfor %}
    </div>

    {% if not object_list %}
    <p class="no-results-message">Записей не найдено.</p>
    {% endif %}
</div>

{% include 'includes/footer.html' %}

</body>
</html>

diary/templates/diary/diary_personal_list.html
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyWay - Мои записи</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        body {
            background: url('{% static 'background/bck.jpg' %}') no-repeat center center fixed;
            background-size: cover;
        }

        .entries-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            gap: 20px;
            margin-top: 50px;
            max-width: 1000px;
            margin-left: auto;
            margin-right: auto;
        }

        .entry {
            background-color: white;
            border: 1px solid #ced4da;
            border-radius: 5px;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            flex: 1 0 200px;
            max-width: 300px;
        }

        .entry h3 {
            margin: 0;
            color: #4e73df;
        }

        .entry-title-link {
            font-size: 1.5rem; /* Увеличенный размер текста */
            color: #4e73df;
            text-decoration: none;
        }

        .entry p {
            margin-top: 10px;
        }

        .btn-primary {
            margin-bottom: 20px;
        }

        .entry img {
            width: 150px;
            height: 150px;
            object-fit: cover;
            border-radius: 5px;
            margin-bottom: 10px;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
        .search-form {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-bottom: 20px;
        }

        .search-input {
            margin-bottom: 21px;
            width: 250px;
            height: 38px;
            margin-right: 10px;
            padding: 0.375rem 0.75rem;
        }

        .search-button {
            height: 38px;
            padding: 0.375rem 0.75rem;
        }

        .private-note {
            color: red;
            font-weight: bold;
            margin-top: 10px;
            text-align: center;
        }
        .no-results-message {
            color: black;
            text-align: center;
            margin-top: 20px;
            font-size: 3rem;
        }
    </style>
</head>

{% include 'includes/inc_menu.html' %}

<div class="container text-center">
    <h1 style="color: white; text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;">
        Мои записи:
    </h1>
    <a href="{% url 'diary:diary_create' %}" class="btn btn-primary">Добавить запись</a>
    <form method="GET" action="{% url 'diary:diary_personal_list' %}" class="search-form">
        <input type="text" name="q" placeholder="Поиск по записям"
               value="{{ request.GET.q }}" class="form-control search-input"/>
        <button type="submit" class="btn btn-primary search-button">Поиск</button>
    </form>
</div>

<div class="container">
    <div class="entries-container">
        {% for diary in object_list %}
        <div class="entry">
            <h3>
                <a href="{% url 'diary:diary_detail' diary.pk %}" class="entry-title-link">{{ diary.title }}</a>
            </h3>
            <p><strong>Дата:</strong> {{ diary.date_event }}</p>
            {% if diary.image %}
            <img src="{{ diary.image.url }}" alt="Изображение записи">
            {% endif %}
            <p>{{ diary.context|truncatewords:10 }}</p>
            {% if not diary.is_active %}
            <p class="private-note">Видно только вам</p>
            {% endif %}
        </div>
        {% endfor %}
    </div>

    {% if not object_list %}
    <p class="no-results-message">Записей не найдено.</p>
    {% endif %}
</div>

{% include 'includes/footer.html' %}

</html>