config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls', namespace='diary')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path
from diary.apps import DiaryConfig
from diary.views import base, DiaryListView, DiaryDetailView, DiaryCreateView, DiaryUpdateView, DiaryDeleteView, \
    DiaryPersonalListView

app_name = DiaryConfig.name

urlpatterns = [
    path('', base, name='base'),
    path('diary/', DiaryListView.as_view(), name='diary_list'),
    path('diary_personal/', DiaryPersonalListView.as_view(), name='diary_personal_list'),
    path('diary/create', DiaryCreateView.as_view(), name='diary_create'),
    path('diary/<int:pk>/', DiaryDetailView.as_view(), name='diary_detail'),
    path('diary/update/<int:pk>/', DiaryUpdateView.as_view(), name='diary_update'),
    path('diary/delete/<int:pk>/', DiaryDeleteView.as_view(), name='diary_delete'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserDetailView, UserUpdateView, UserDeleteView, \
    UserListView, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),
    path('reset_password/', reset_password, name='reset_password'),

    path('users/', UserListView.as_view(), name='user_list'),
    path('users/<int:pk>', UserDetailView.as_view(), name='user_detail'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
]

diary/models.py
from django.db import models
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Diary(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    image = models.ImageField(upload_to='diary/image', verbose_name='Превью события', **NULLABLE)
    context = models.TextField(verbose_name='Описание события')
    date_event = models.CharField(max_length=20, verbose_name='Дата события', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи', **NULLABLE)
    is_active = models.BooleanField(default=True, help_text='Разрешить эту запись видеть всем?')
    owner = models.ForeignKey(User, verbose_name='Владелец', on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Запись дневника'
        verbose_name_plural = 'Записи дневника'

diary/forms.py
from django.forms import ModelForm
from diary.models import Diary


class DiaryUpdateForm(ModelForm):
    class Meta:
        model = Diary
        fields = ('title', 'image', 'context', 'date_event', 'is_active')

diary/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from diary.forms import DiaryUpdateForm
from diary.models import Diary


def base(request):
    return render(request, 'base.html')


class DiaryListView(LoginRequiredMixin, ListView):
    model = Diary
    template_name = 'diary/diary_list.html'

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        if self.request.user.is_superuser:
            qs = Diary.objects.all()
        else:
            qs = Diary.objects.filter(is_active=True)
        if query:
            qs = qs.filter(Q(title__icontains=query) | Q(context__icontains=query))
        return qs.order_by('-created_at')


class DiaryDetailView(LoginRequiredMixin, DetailView):
    model = Diary
    template_name = 'diary/diary_detail.html'


class DiaryCreateView(CreateView):
    model = Diary
    fields = ('title', 'image', 'context', 'date_event', 'is_active')
    success_url = reverse_lazy('diary:diary_list')

    def form_valid(self, form):
        diary = form.save()
        user = self.request.user
        diary.owner = user
        diary.save()
        return super().form_valid(form)


class DiaryUpdateView(LoginRequiredMixin, UpdateView):
    model = Diary
    form_class = DiaryUpdateForm
    success_url = reverse_lazy('diary:diary_list')

    def get_queryset(self):
        return Diary.objects.filter(owner=self.request.user)


class DiaryDeleteView(LoginRequiredMixin, DeleteView):
    model = Diary
    success_url = reverse_lazy('diary:diary_list')


class DiaryPersonalListView(LoginRequiredMixin, ListView):
    model = Diary
    template_name = 'diary/diary_personal_list.html'

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        qs = Diary.objects.filter(owner=self.request.user).order_by('-created_at')
        if query:
            qs = qs.filter(Q(title__icontains=query) | Q(context__icontains=query))
        return qs.order_by('-created_at')

diary/templates/includes/footer.html
{% load static %}
<footer class="text-center mt-5"
        style="color: white; text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;">
    <p>&copy; <span id="year"></span> MyWay. Все права защищены.</p>
</footer>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script>
    document.getElementById("year").textContent = new Date().getFullYear();
</script>

diary/templates/includes/inc_menu.html
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-size: cover;">
    <a class="btn btn-primary me-3" href="{% url 'diary:diary_personal_list' %}" style="margin-right: 10px;">Мои
        записи</a>
    <a class="btn btn-primary" href="{% url 'diary:diary_list' %}" style="margin-left: 10px; margin-right: 10px;">Записи
        всех пользователей</a>
    {% if user.is_superuser %}
    <a class="btn btn-primary" href="{% url 'users:user_list' %}" style="margin-left: 10px; margin-right: 10px;">
        Пользователи
    </a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <div class="d-flex align-items-center">
                {% if user.avatar %}
                <img src="{{ user.avatar.url }}" alt="Аватар"
                     style="width: 50px; height: 50px; border-radius: 50%; margin-right: 10px;">
                {% endif %}
                <a class="navbar-text me-3" href="{% url 'users:user_detail' user.pk %}"
                   style="text-decoration: none; color: white; background-color: transparent; margin-right: 10px; text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;">
                    {% if user.nick_name %}
                    {{ user.nick_name }}
                    {% else %}
                    {{ user.email }}
                    {% endif %}
                </a>
                <a class="btn btn-secondary" href="{% url 'users:logout' %}">Выход из аккаунта</a>
            </div>
        </ul>
    </div>
</nav>
{% endif %}